version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000" 

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80" # Map host port 80 to container port 80
    depends_on:
      - server # Ensure the server starts before the client

